language: python
python:
  - "3.7-dev"

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="Plateforme_Projet8.settings.travis"

services:
  - postgresql

script:
  - manage.py test