language: python
python:
  - "3.7-dev"

env:
  - DJANGO=2.0.7 DB=postgre

install:
  - pip install -q Django==$DJANGO
  - pip install -q -r requirements.txt

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test