language: python
python:
  - "3.7-dev"

env:
  - DJANGO=2.0.7 DB=postgre

install:
  - pip install -q Django==$DJANGO
  - python setyp.py -q install
  - pip install -q -r requirements.txt

script: python manage.py test