language: python
python:
  - "3.7-dev"

before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=Plateforme_Projet8.settings.travis

before_script:
 - chmod +x gradlew

script:
  - ./manage.py test