# Generated by Django 2.0.7 on 2018-08-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutrition',
            field=models.URLField(default='https://static.openfoodfacts.org/images/products/327/016/089/0385/nutrition_fr.11.400.jpg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='url_off',
            field=models.URLField(default='https://fr-en.openfoodfa…385/veggie-burger-picard'),
            preserve_default=False,
        ),
    ]
