# Generated by Django 2.0.7 on 2018-08-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20180803_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('product', models.IntegerField()),
                ('product_sub', models.IntegerField()),
            ],
        ),
    ]
