# Generated by Django 2.0.7 on 2018-08-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_association'),
    ]

    operations = [
        migrations.RenameField(
            model_name='association',
            old_name='product',
            new_name='asso_product',
        ),
        migrations.RenameField(
            model_name='association',
            old_name='product_sub',
            new_name='asso_product_sub',
        ),
        migrations.RenameField(
            model_name='association',
            old_name='user',
            new_name='asso_user',
        ),
    ]
