# Generated by Django 2.0.7 on 2018-09-10 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_auto_20180807_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='asso_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product'),
        ),
        migrations.AlterField(
            model_name='association',
            name='asso_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
