# Generated by Django 2.0.7 on 2018-09-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20180910_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='asso_user',
            field=models.IntegerField(),
        ),
    ]
