# Generated by Django 2.0.7 on 2018-09-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20180921_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='asso_product',
            field=models.IntegerField(),
        ),
    ]
